Update ore-loot-tables.md with xp method for non experimental
Bedrock-OSS/bedrock-wiki-vite pull request #666
Opened 2023-06-29 19:08 UTC by Keyyard

I have added a method to gain xp orbs for blocks without turning on the experimental mode.

2023-06-30 01:30 UTC, Keyyard reviewed
I have fixed the language part for better merging

2023-07-10 15:13 UTC, QuazChick requested changes
Some instances of `my_xp_structure` remain unchanged.

2023-07-10 15:13 UTC, QuazChick commented on docs/blocks/ore-loot-tables.md
> +This function will execute for any item entity with the name "Raw Silver", which is ``wiki:raw_silver`` item ID that does not have the "xp" tag. It loads the "my_xp_structure" at the item's location
Change `my_xp_structure` to `ore_xp_reward`.

2023-07-10 15:13 UTC, QuazChick commented on docs/blocks/ore-loot-tables.md
> +This function will execute for any item entity with the name "Barrier" (our dummy item). It loads a structure called "my_xp_structure" at the item's location and then kills the item.
Change `my_xp_structure` to `ore_xp_reward`.

2023-07-10 15:13 UTC, QuazChick commented on docs/blocks/ore-loot-tables.md
> +execute as @e[type=item,name="Barrier"] at @s run structure load my_xp_structure ~~~
Change `my_xp_structure` to `ore_xp_reward`.

2023-08-09 07:01 UTC, merged