binary method to avoid hitting properties limit
Bedrock-OSS/bedrock-wiki-vite pull request #712
Opened 2023-08-30 02:59 UTC by AntiMod-Noob

its binary calculation method with simple maths to use properties to save a number
ranging from 0 to 255 in case of 2 properties.
ranging from 0 to 4095 in case of 3 properties

max value = 16^number of properties -1

2023-08-31 17:12 UTC, SmokeyStack requested changes
In general, make sure the first letter of a sentence is capitalized.

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +![Image describing how it works](https://github.com/Bedrock-OSS/bedrock-wiki/assets/109032503/a7d00866-2120-49d3-ba85-5b92a4e831d8)
Please use relative paths instead of absolute paths like `![](assets/path/to/image)` per our https://wiki.bedrock.dev/contribute-style.html#working-with-markdown

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +In same way we can use 3 properties to produce a single number that can range from 0 to 4095
Please change it to `Using the same method, we can use 3 properties to produce a single number that can range from 0 to 4095.`

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +## Value Range Calculation
You can change it to
> You can calculate the maximum number of properties by using this equation: `16^n - 1`, where `n` is the number of properties you have.

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +### create properties
Change `create` to `Create`

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +### reading value
Change `reading values` to `Reading values`

2023-08-31 17:12 UTC, SmokeyStack commented on docs/blocks/avoiding-properties-limit.md
> +### Storing value
Change `value` to `values`

2023-09-04 00:23 UTC, AntiMod-Noob reviewed
All parts done. For image which I used i dont know how to fix, however i made its path relative as you told.
the image is at ![](https://github.com/Bedrock-OSS/bedrock-wiki/assets/109032503/a7d00866-2120-49d3-ba85-5b92a4e831d8)

2023-09-16 10:01 UTC, AntiMod-Noob commented
hello? can i know whats the problem in this now

2023-09-21 22:56 UTC, AntiMod-Noob reviewed
I uploaded image within repository and made path relative

2023-12-10 23:20 UTC, merged