Update placement-prevention.md
Bedrock-OSS/bedrock-wiki-vite pull request #741
Opened 2023-09-30 13:05 UTC by kumja1

Added tutorial for beta methods, and seperated article into two sections,beta and stable

2023-09-30 13:29 UTC, kumja1 commented on docs/scripting/placement-prevention.md
> +
guess I didn't fix, I'll leave it up to the mods

2023-11-01 16:36 UTC, SmokeyStack requested changes

2023-11-01 16:36 UTC, SmokeyStack commented on docs/scripting/placement-prevention.md
> +### Stable Methods
Please remove this line. It is breaking the frontmatter generator

2023-11-02 19:57 UTC, SmokeyStack approved these changes

2023-11-02 19:57 UTC, merged