Update block-events.md
Bedrock-OSS/bedrock-wiki-vite pull request #752
Opened 2023-10-27 17:57 UTC by VactricaKing

I have discovered a better way to place the blocks using "set_block" and "set_block_at_pos" it seems almost nobody knows it, so I contribute something that in my opinion will greatly improve how to make a double block.

2023-10-28 01:51 UTC, VactricaKing commented
@SmokeyStack Why is it not accepted yet? Is there a problem with my contribution?

2023-11-01 16:38 UTC, SmokeyStack requested changes

2023-11-01 16:38 UTC, SmokeyStack commented on docs/blocks/block-events.md
> -      "block_type": "minecraft:grass"
Please make this a separate codeblock and subheader. That way we can have a normal `set_block` and one with block states

2023-11-01 16:38 UTC, SmokeyStack commented on docs/blocks/block-events.md
> -"wiki:generate_stone_above": {
Please make this a separate codeblock and subheader. That way we can have a normal set_block and one with block states

2023-11-03 01:36 UTC, VactricaKing commented
@SmokeyStack Done!

2023-11-09 02:57 UTC, SmokeyStack approved these changes

2023-11-09 03:03 UTC, merged