Holiday Creator Features Rewrite
Bedrock-OSS/bedrock-wiki-vite pull request #835
Opened 2024-04-09 16:37 UTC by SmokeyStack

This PR aims to resolve: https://github.com/Bedrock-OSS/bedrock-wiki/projects/3

2024-08-16 15:27 UTC, ThomasOrs commented on .prettierrc.json
> -	"printWidth": 80,
Change from default print width?

2024-08-16 16:20 UTC, ThomasOrs requested changes
Looks good overall! Some cases where some HCF examples / warnings still appear.
In some places it is not clear that post 1.21.20 there HCF examples / methods 100% will not work.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/block-tags.md
The Experiemntal warning for the `q.block` molang queries is out of date. These established in 1.20.60, the toggle was also removed. Might be worth grabbing as part of this pages changes.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/block-states.md
File still contains `Event Response
` with mention of turning on HCF.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/block-models.md
> +            <WikiImage src="/assets/images/blocks/block-models/paper_bag.png" style="background-color: rgb(0,0,0,0.15);" pixelated="true" width="128"/>
This imagine and the <br> tag are displaying as part of the code highlight. 
![image](https://github.com/user-attachments/assets/866a8746-b39c-4a1e-86fb-06d4c3de1d67)

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/block-models.md
> +            <WikiImage src="/assets/images/blocks/block-models/paper_bag_bottom_fold.png" style="background-color: rgb(0,0,0,0.15);" pixelated="true" width="128"/>
See above comment

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/precise-rotation.md
Page still has a requires HCF warning

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/rotatable-blocks.md
Page contains HCF example?
Log rotation example with Unit Cube

2024-08-16 16:20 UTC, ThomasOrs commented on docs/blocks/custom-fluids.md
Contains a warning for requires HCF for Molang queries - Not needed
Contains queued_ticking which no longer exists
Should this be hidden?

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Block Placer item component. Items with this component will place a block when used. Experimental toggles required: Holiday Creator Features (in format versions before 1.20.10).
Should experimental toggles required be included here? The toggle no longer exists 🤔

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Cool down time for a component. After use, all items in a specified 'cool down category' become unusable for a determined amount of time defined in the component. In format versions before 1.20.10, t
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Defines the text shown when an item name is shown, such as hover text. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features' experimental toggle.
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Determines how much damage the item can take before breaking, and allows the item to be combined in crafting. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Allows the item to place specified entities into the world. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features' experimental toggle.
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Allows the item to be used as fuel in a furnace to 'cook' other items. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features' experimental toggle.
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Determines the icon to represent the item in the UI and elsewhere. In format versions before 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle.
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Projectile item component. Projectile items shoot out, like an arrow. In format versions prior to 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle.
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Repairable item component: Determines which items can be used to repair a defined item, as well as the amount of durability specified items will repair. In format versions prior to 1.20.10, this comp
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Shooter Item Component. Must have the `minecraft:use_modifiers` component in order to function properly. In format versions prior to 1.20.10, this component requires the 'Holiday Creator Features' ex
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Throwable item component. Throwable items, such as a snowball. In format versions prior to 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle. Item must have the `min
See above

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/item-components.md
> +Determines where the item can be worn. If any non-hand slot is chosen, the max stack size is set to 1. Experimental toggles required: Holiday Creator Features.
See above / this one does not say what version it was introduced at all.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/troubleshooting-items.md
One of the tip implies all items 1.16.100 are experimental, which is inaccurate.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/custom-armor.md
> +    "format_version": "1.16.100",
Still has an old-format version

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/custom-armor.md
> +    "format_version": "1.16.100",
Old format version

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/custom-armor.md
> +    "format_version": "1.16.100",
old format version

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/custom-armor.md
> +    "format_version": "1.16.100",
Old format version

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/equipped-item-commands.md
Page contains mention of requiring HCF

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/tool-durability.md
It doesn't seem clear on this page that the Item Event method no longer works.

2024-08-16 16:20 UTC, ThomasOrs commented on docs/items/tool-durability.md
There is a warning that this uses experimental scripts `1.9.0-beta` are the apis now stable?

2024-08-16 16:21 UTC, ThomasOrs commented on docs/items/item-components.md
> +Block Placer item component. Items with this component will place a block when used. Experimental toggles required: Holiday Creator Features (in format versions before 1.20.10).
Should this instead be ` Requires format version 1.20.10 or above`?

2024-08-20 17:42 UTC, SmokeyStack reviewed
Applied suggestions

2024-08-20 22:10 UTC, merged

2024-08-21 00:40 UTC, ThomasOrs commented
:shipit: