Update useful-links.md
Bedrock-OSS/bedrock-wiki-vite pull request #905
Opened 2024-08-30 23:19 UTC by zheaEvyline

- Reordered all lists in alphabetical order (excluding starred)
- Linked Nine Slice Visualiser UI Tool by Minato under **Bedrock Tools Websites**
- Starred Snowstorm under **Discord Links** (since blockbench and bridge seem to be starred as well)

2024-09-20 02:08 UTC, SmokeyStack requested changes

2024-09-20 02:08 UTC, SmokeyStack commented on docs/commands/block-entities.md
Please use `wiki` as a namespace for all guides.

2024-09-20 02:08 UTC, SmokeyStack commented on docs/commands/derangement-function.md
The title for this article doesn't fit. Rearrange or spreadplayers is a better name.

2024-09-20 02:08 UTC, SmokeyStack commented on docs/commands/derangement-function.md
> +For example, if Player1 was at `0,0,1`, Player2 at `0,0,2`, and Player3 at `0,0,3`, Player1 can only be relocated to `0,0,2` or `0,0,3`. The same rule applies to all other players.
Please have commas after each coordinates: `0, 0, 1`

2024-09-20 02:08 UTC, SmokeyStack commented on docs/commands/movement-detections.md
All H3 headers comments should still start with capitalization. Example: `Mark current point` rather than `mark current point`

2024-09-20 09:05 UTC, zheaEvyline commented on docs/commands/movement-detections.md
Yep, this has been followed for all comments in codeblocks that aren't mcfunctions. For H3 comments in codeblocks that are mcfunctions, `lowercase` has been used to be consistent with the "Comments in Functions" Style Guide: https://bedrockcommands.github.io/meta/style-guide.html#comments-in-functions

2024-09-22 03:35 UTC, SmokeyStack commented on docs/commands/movement-detections.md
Not a fan of this style guide. There's really no reason to make H3 all lower case, just the first word being capitalised just like a normal sentence would be much favourable.

2024-09-22 08:38 UTC, zheaEvyline commented on docs/commands/movement-detections.md
Hmm that might be more favourable. I have implemented the change 👀

2024-09-30 17:13 UTC, QuazChick approved these changes
Can't find any other issues, looks good!

2024-09-30 17:14 UTC, merged