More docs on NBTs
Bedrock-OSS/bedrock-wiki-vite pull request #922
Opened 2024-10-11 18:45 UTC by theaddonn

- Added Documentation on Network-Little-Endian integer encoding (https://github.com/Bedrock-OSS/bedrock-wiki/issues/855)
- Fixed several typos
- Cleaned up layout
- Added more precise descriptions for Datatype
- Added list of existing NBT libraries sorted by programming language

Further questions:
- Should I also document extra encodings not commonly found in Bedrock Edition such as `Big Endian` and `Network Big Endian`? - Is there any way to enable sorting for tables?

2024-10-11 23:26 UTC, SmokeyStack requested changes
Really not a fan of the random new lines in the markdown files. While it won't affect rendering, it is vastly formatted differently than our other files.

2024-10-11 23:33 UTC, theaddonn commented
Are you sure? I just did it because it made editing easier.. long lines are hard to read in your editor and can be difficult in the long run (This auto formatting was even directly done by my ide, sorrry). But I can surely change it

2024-10-12 00:27 UTC, theaddonn commented
Should be all fixed now, pretty as we like it

2024-10-13 15:31 UTC, SmokeyStack requested changes

2024-10-13 15:31 UTC, SmokeyStack commented on docs/nbt/nbt-in-depth.md
> +then the significant type of the property that we will read. The read property is always followed by the name (key), which needs to be read as a [String](#reading-Strings), and after the String is re
`reading-Strings` -> `reading-strings`

2024-10-13 15:31 UTC, SmokeyStack commented on docs/nbt/nbt-in-depth.md
>  ## Minecraft BE NBT files
Changed `Minecraft BE` to `Bedrock`

2024-10-13 15:31 UTC, SmokeyStack commented on docs/nbt/nbt-in-depth.md
> +When reading Minecraft NBT files, it is always important to be careful if there is no Bedrock Header at the beginning of the file, see [Bedrock NBT Header](#bedrock-nbt-file-header), but not all MCBE
Likewise, change all `MCBE` to just `Bedrock`

2024-10-13 15:31 UTC, SmokeyStack commented on docs/nbt/nbt-in-depth.md
>  ## Little-Endian
Does little endian need a `-`?

2024-10-13 15:31 UTC, SmokeyStack commented on docs/nbt/nbt-in-depth.md
> +## Network-Little-Endian
Does network little endian need a `-`?

2024-10-13 20:55 UTC, theaddonn commented on docs/nbt/nbt-in-depth.md
>  ## Little-Endian
nope, and it is removed now

2024-10-13 20:56 UTC, theaddonn commented
All resolved now, but still..
Should I also document extra encodings not commonly (aka Java only) found in Bedrock Edition such as `Big Endian` and `Network Big Endian`?

2024-10-13 23:11 UTC, SmokeyStack approved these changes

2024-10-13 23:11 UTC, SmokeyStack commented
> All resolved now, but still.. Should I also document extra encodings not commonly (aka Java only) found in Bedrock Edition such as `Big Endian` and `Network Big Endian`?

We can do this in a different PR. Going to merge this PR now.

2024-10-13 23:12 UTC, merged