Update Blocks and Items Sections to v1.21.40
Bedrock-OSS/bedrock-wiki-vite pull request #928
Opened 2024-10-21 13:26 UTC by QuazChick

## Blocks
- Updated all examples to format version 1.21.40.
- Added experimental block items documentation.
- Added `minecraft:redstone_conductivity` component.

## Items
- Updated all examples to format version 1.21.40.
- Removed outdated troubleshooting information.
- Added `minecraft:durability_sensor` component.
- Added `minecraft:damage_absorption` component.
- Added `minecraft:dyeable` component.
- Added `minecraft:rarity` component.
- Added minecraft:storage_item component.
- Added minecraft:bundle_interaction component.

2024-10-21 16:23 UTC, SmokeyStack requested changes

2024-10-21 16:23 UTC, SmokeyStack commented on docs/blocks/block-items.md
Not really a fan of the title of the page/file name. How about `rendering-blocks-as-items`? Sure it's longer but it's descriptive and you can tell what the page will be about based on just the URL and title.

2024-10-21 17:04 UTC, SmokeyStack requested changes

2024-10-21 17:04 UTC, SmokeyStack commented on docs/items/item-components.md
Don't forget to update `icon` as well

2024-10-22 08:32 UTC, QuazChick commented on docs/blocks/block-items.md
Giving the block an icon was an example, the page serves to explain what a block item is and gives a way to modify their components. Maybe examples with different components could be added?

2024-10-22 12:25 UTC, SmokeyStack commented on docs/blocks/block-items.md
Such as using tags for recipes, fuel, and mob heads? More examples would be great, but Block Items isn't really descriptive. `overriding-blocks-itemstack`?

2024-10-22 16:45 UTC, QuazChick commented on docs/blocks/block-items.md
I think Block Items is descriptive for a page about the item types related to blocks, it's also the phrase Mojang uses to refer to them (block item config, `replace_block_item`).

Given that the page isn't purely focused on replacing block items, I think it would be wrong to name the entire page around that concept. We can still link to that part in a way that is readable from the URL `block-items#replacing-block-items`.

2024-10-22 17:31 UTC, SmokeyStack commented on docs/blocks/block-items.md
It's only descriptive since we both know what Block Items are from Java's source code and what Mojang calls them. I think `blocks-itemstack` might be more descriptive personally.

2024-10-22 18:47 UTC, merged