Added a Structure Presentation Pack.
Bedrock-OSS/bedrock-wiki-vite pull request #935
Opened 2024-10-26 23:57 UTC by MinecraftBedrockArabic

Added a Structure Presentation Pack that allow creators to change the structure preview background and disable the preview arrows.

2024-10-27 11:35 UTC, SuperLlama88888 commented on docs/public/assets/images/visuals/structure-presentation/structure_presentation_pack.png
I love this! Could the gradients be on the buttons as well?

2024-10-27 11:38 UTC, MinecraftBedrockArabic commented on docs/public/assets/images/visuals/structure-presentation/structure_presentation_pack.png
> I love this! Could the gradients be on the buttons as well?

sure. maybe in a future update

2024-10-28 18:33 UTC, QuazChick requested changes

2024-10-28 18:33 UTC, QuazChick commented on docs/visuals/structure-presentation.md
> +Or you can use **Structure Presentation Pack** by @minato4743 to simplify the process. It include some default colors and gradient as will as toggle to hide the preview arrows.
Some grammatical issues
```suggestion
Or you can use the **Structure Presentation Pack** by @minato4743 to simplify the process. It includes some default colors and gradients as well as a toggle to hide the preview arrows.
```

2024-10-30 16:56 UTC, merged