Create WebSocket
Bedrock-OSS/bedrock-wiki-vite pull request #956
Opened 2024-12-10 00:08 UTC by MinedPlumr

2024-12-27 03:16 UTC, SmokeyStack requested changes

2024-12-27 03:16 UTC, SmokeyStack commented on docs/WebSocket/index.md
Please make folders use `snake_case`, in this case, `web_socket`.

2024-12-27 03:16 UTC, SmokeyStack commented on docs/WebSocket/index.md
> +title: Getiing Started
Please fix the typo.

2024-12-27 13:56 UTC, theaddonn commented
Wouldn't it make sense to put this into the Concepts category instead of creating a new one?

2025-01-05 18:27 UTC, QuazChick commented
This page needs to be moved into an existing section. Files at `docs/*/index.md` are only set up to handle section title and category definitions.

2025-01-19 14:09 UTC, closed without merging